level1:
  name: "500,000 токенов"
  description: "С лимитом в 500,000 токенов вы можете насладиться обширными беседами и провести небольшие исследования в мире диалогов с ChatGPT"
  price: 499
  currency: RUB
  token_amount: 500000
level2:
  name: "1,000,000 токенов"
  description: "С 1,000,000 токенами вы открываете перед собой бескрайний океан творческих возможностей, позволяя создавать не только обширные диалоги, но и эпические истории с героями и сюжетными поворотами."
  price: 699
  currency: RUB
  token_amount: 1000000
level3:
  name: "3,000,000"
  description: "С 3,000,000 токенами вы становитесь творцом своего собственного литературного мира, способного строить сложные сюжеты, развивать персонажей и создавать уникальные фантастические миры."
  price: 1599
  currency: RUB
  token_amount: 3000000
level4:
  name: "10,000,000"
  description: "С этим великолепным запасом токенов перед вами открывается бескрайний океан творческих возможностей, где вы можете создавать эпические саги, исследовать различные аспекты миров и полностью погрузиться в свой уникальный литературный космос."
  price: 4599
  currency: RUB
  token_amount: 10000000
